#xrun -access +rwc -input ../shm.tcl ex1_procedural_identifier.sv
#xrun -access +rwc -input ../shm.tcl ex2_procedural_unnamedblocks.sv
#xrun -access +rwc -input ../shm.tcl ex3_procedural_variables_forloop.sv
#xrun -access +rwc -input ../shm.tcl ex4_procedural_foreach.sv
#xrun -access +rwc -input ../shm.tcl ex5_procedural_dowhile.sv
#xrun -access +rwc -input ../shm.tcl ex6_procedural_jump.sv
#xrun -access +rwc -input ../shm.tcl ex7_procedural_verilogcase.sv
#xrun -access +rwc -input ../shm.tcl ex8_procedural_prioritycase.sv
#xrun -access +rwc -input ../shm.tcl ex8_1_procedural_uniquecase.sv
#xrun -access +rwc -input ../shm.tcl ex9_procedural_priorityif.sv
#xrun -access +rwc -input ../shm.tcl ex10_procedural_uniqueif.sv
#xrun -access +rwc -input ../shm.tcl ex11_procedural_iff.sv
#xrun -access +rwc -input ../shm.tcl ex12_procedural_hwmodeling.sv
#xrun -access +rwc -input ../shm.tcl ex13_procedural_always_comb.sv
#xrun -access +rwc -input ../shm.tcl ex13_1_procedural_always_comb_comparison.sv
#xrun -access +rwc -input ../shm.tcl ex14_procedural_always_latch.sv
#xrun -access +rwc -input ../shm.tcl ex15_procedural_always_ff.sv
#xrun -access +rwc -input ../shm.tcl ex16_procedural_quiz1.sv
#xrun -access +rwc -input ../shm.tcl ex16_procedural_quiz2.sv
#xrun -access +rwc -input ../shm.tcl ex16_procedural_quiz3.sv
#xrun -access +rwc -input ../shm.tcl ex16_procedural_quiz4.sv
#xrun -access +rwc -input ../shm.tcl ex16_procedural_quiz5.sv
#xrun -access +rwc -input ../shm.tcl ex16_procedural_quiz6.sv
#xrun -access +rwc -input ../shm.tcl ex16_procedural_quiz7.sv
