#xrun -access +rwc -input ../shm.tcl ex01_0_procedural_identifier.sv
#xrun -access +rwc -input ../shm.tcl ex02_0_procedural_unnamedblocks.sv
#xrun -access +rwc -input ../shm.tcl ex03_0_procedural_variables_forloop.sv
#xrun -access +rwc -input ../shm.tcl ex04_0_procedural_foreach.sv
#xrun -access +rwc -input ../shm.tcl ex05_0_procedural_dowhile.sv
#xrun -access +rwc -input ../shm.tcl ex06_0_procedural_jump.sv
#xrun -access +rwc -input ../shm.tcl ex07_0_procedural_verilogcase.sv
#xrun -access +rwc -input ../shm.tcl ex08_0_procedural_prioritycase.sv
#xrun -access +rwc -input ../shm.tcl ex08_1_procedural_uniquecase.sv
#xrun -access +rwc -input ../shm.tcl ex09_0_procedural_priorityif.sv
#xrun -access +rwc -input ../shm.tcl ex10_0_procedural_uniqueif.sv
#xrun -access +rwc -input ../shm.tcl ex11_0_procedural_iff.sv
#xrun -access +rwc -input ../shm.tcl ex12_0_procedural_hwmodeling.sv
#xrun -access +rwc -input ../shm.tcl ex13_0_procedural_always_comb.sv
#xrun -access +rwc -input ../shm.tcl ex13_1_procedural_always_comb_comparison.sv
#xrun -access +rwc -input ../shm.tcl ex14_0_procedural_always_latch.sv
#xrun -access +rwc -input ../shm.tcl ex15_0_procedural_always_ff.sv
#xrun -access +rwc -input ../shm.tcl ex16_0_procedural_quiz1.sv
#xrun -access +rwc -input ../shm.tcl ex16_0_procedural_quiz2.sv
#xrun -access +rwc -input ../shm.tcl ex16_0_procedural_quiz3.sv
#xrun -access +rwc -input ../shm.tcl ex16_0_procedural_quiz4.sv
#xrun -access +rwc -input ../shm.tcl ex16_0_procedural_quiz5.sv
#xrun -access +rwc -input ../shm.tcl ex16_0_procedural_quiz6.sv
#xrun -access +rwc -input ../shm.tcl ex16_0_procedural_quiz7.sv
