#xrun -access +rwc -input ../shm.tcl ex01_0_interface_intro.sv
#xrun -access +rwc -input ../shm.tcl ex02_0_interface_example.sv
#xrun -access +rwc -input ../shm.tcl ex03_0_interface_connecting.sv
#xrun -access +rwc -input ../shm.tcl ex04_0_interface_port.sv
#xrun -access +rwc -input ../shm.tcl ex05_0_interface_instance_identifier.sv
#xrun -access +rwc -input ../shm.tcl ex06_0_interface_define_port.sv
#xrun -access +rwc -input ../shm.tcl ex07_0_interface_port_application.sv
#xrun -access +rwc -input ../shm.tcl ex08_0_interface_port_parameter.sv
#xrun -access +rwc -input ../shm.tcl ex09_0_interface_modport.sv
#xrun -access +rwc -input ../shm.tcl ex09_0_1_interface_modport_instance.sv
#xrun -access +rwc -input ../shm.tcl ex09_0_2_interface_modport_binding.sv
#xrun -access +rwc -input ../shm.tcl ex10_0_interface_method.sv
#xrun -access +rwc -input ../shm.tcl ex10_1_interface_methodtask.sv
#xrun -access +rwc -input ../shm.tcl ex10_2_interface_methodtaskmodport.sv
xrun -access +rwc -input ../shm.tcl ex11_0_interface_generic_interface.sv
#xrun -access +rwc -input ../shm.tcl ex12_0_interface_quiz.sv
