xrun -access +rwc -input ../shm.tcl ex01_0_datatype_logic.sv
#xrun -access +rwc -input ../shm.tcl ex02_0_datatype_bitlogic.sv
#run -access +rwc -input ../shm.tcl ex03_0_datatype_logicrelaxation.sv
#xrun -access +rwc -input ../shm.tcl ex04_0_datatype_verilogexam.sv
#xrun -access +rwc -input ../shm.tcl ex04_1_datatype_relaxedexam.sv
#xrun -access +rwc -input ../shm.tcl ex04_2_datatype_variableassign.sv
#xrun -access +rwc -input ../shm.tcl ex05_0_datatype_alwayscomb.sv
#xrun -access +rwc -input ../shm.tcl ex06_0_datatype_unsized_literals.sv
#xrun -access +rwc -input ../shm.tcl ex07_0_datatype_timeliterals.sv
#xrun -access +rwc -input ../shm.tcl ex08_0_datatype_timeunit.sv