#xrun -access +rwc -input ../shm.tcl ex01_0_dvfeatures_intro.sv
#xrun -access +rwc -input ../shm.tcl ex02_0_dvfeatures_string_method.sv
#xrun -access +rwc -input ../shm.tcl ex03_0_dvfeatures_immediate_assertion.sv
#xrun -access +rwc -input ../shm.tcl ex04_0_dvfeatures_action_block.sv
#xrun -access +rwc -input ../shm.tcl ex05_0_dvfeatures_assertion_severity.sv
#xrun -access +rwc -input ../shm.tcl ex06_0_dvfeatures_assertion_example.sv
#xrun -access +rwc -input ../shm.tcl ex07_0_dvfeatures_assertion_comparison.sv
#xrun -access +rwc -input ../shm.tcl ex08_0_dvfeatures_forkjoin_intro.sv
#xrun -access +rwc -input ../shm.tcl ex09_0_dvfeatures_forkjoin_disablewait.sv
#xrun -access +rwc -input ../shm.tcl ex10_0_dvfeatures_forkjoin_disable_ex1.sv
xrun -access +rwc -input ../shm.tcl ex11_0_dvfeatures_forkjoin_disable_ex2.sv
#xrun -access +rwc -input ../shm.tcl ex12_0_dvfeatures_forkjoin_disable_ex3.sv
