#xrun -access +rwc -input ../shm.tcl ex1_class_intro.sv
#xrun -access +rwc -input ../shm.tcl ex2_class_object.sv
#xrun -access +rwc -input ../shm.tcl ex3_class_variable.sv
#xrun -access +rwc -input ../shm.tcl ex4_class_comparison.sv
#xrun -access +rwc -input ../shm.tcl ex5_class_accessbydot.sv
#xrun -access +rwc -input ../shm.tcl ex6_class_externalmethod.sv
#xrun -access +rwc -input ../shm.tcl ex7_class_constructor.sv
#xrun -access +rwc -input ../shm.tcl ex8_class_example_classusage.sv
#xrun -access +rwc -input ../shm.tcl ex9_class_this.sv
#xrun -access +rwc -input ../shm.tcl ex10_class_staticmember.sv
#xrun -access +rwc -input ../shm.tcl ex11_class_staticmethod.sv
#xrun -access +rwc -input ../shm.tcl ex12_class_aggregation.sv
#xrun -access +rwc -input ../shm.tcl ex13_class_inheritance.sv
#xrun -access +rwc -input ../shm.tcl ex14_class_inheritance_example.sv
#xrun -access +rwc -input ../shm.tcl ex15_class_inheritance_constructor_example.sv
#xrun -access +rwc -input ../shm.tcl ex16_class_inheritance_multilayer.sv
#xrun -access +rwc -input ../shm.tcl ex17_class_data_encapsulation.sv
#xrun -access +rwc -input ../shm.tcl ex18_class_parameterized.sv
