#xrun -access +rwc -input ../shm.tcl ex01_0_class_intro.sv
#xrun -access +rwc -input ../shm.tcl ex02_0_class_object.sv
#xrun -access +rwc -input ../shm.tcl ex03_0_class_variable.sv
#xrun -access +rwc -input ../shm.tcl ex04_0_class_comparison.sv
#xrun -access +rwc -input ../shm.tcl ex05_0_class_accessbydot.sv
#xrun -access +rwc -input ../shm.tcl ex06_0_class_externalmethod.sv
#xrun -access +rwc -input ../shm.tcl ex07_0_class_constructor.sv
#xrun -access +rwc -input ../shm.tcl ex08_0_class_example_classusage.sv
#xrun -access +rwc -input ../shm.tcl ex09_0_class_this.sv
#xrun -access +rwc -input ../shm.tcl ex10_0_class_staticmember.sv
#xrun -access +rwc -input ../shm.tcl ex11_0_class_staticmethod.sv
#xrun -access +rwc -input ../shm.tcl ex12_0_class_aggregation.sv
#xrun -access +rwc -input ../shm.tcl ex13_0_class_inheritance.sv
#xrun -access +rwc -input ../shm.tcl ex14_0_class_inheritance_example.sv
xrun -access +rwc -input ../shm.tcl ex15_0_class_inheritance_constructor_example.sv
#xrun -access +rwc -input ../shm.tcl ex16_0_class_inheritance_multilayer.sv
#xrun -access +rwc -input ../shm.tcl ex17_0_class_data_encapsulation.sv
#xrun -access +rwc -input ../shm.tcl ex18_0_class_parameterized.sv
