#xrun -access +rwc -input ../shm.tcl ex01_0_polymor_intro.sv
#xrun -access +rwc -input ../shm.tcl ex02_0_polymor_copyparentinst.sv
#xrun -access +rwc -input ../shm.tcl ex03_0_polymor_usingcast.sv
#xrun -access +rwc -input ../shm.tcl ex04_0_polymor_advantage.sv
xrun -access +rwc -input ../shm.tcl ex04_1_polymor_advantage_extra.sv
#xrun -access +rwc -input ../shm.tcl ex05_0_polymor_classmemberaccess.sv
#xrun -access +rwc -input ../shm.tcl ex06_0_polymor_virtualmethod.sv
#xrun -access +rwc -input ../shm.tcl ex06_1_polymor_virtualmethod_extra.sv
#xrun -access +rwc -input ../shm.tcl ex07_0_polymor_resolveclassmethodaccess.sv
#xrun -access +rwc -input ../shm.tcl ex08_0_polymor_purevirtual.sv
