xrun -access +rwc -input ../shm.tcl ex1_polymor_intro.sv
#xrun -access +rwc -input ../shm.tcl ex2_polymor_copyparentinst.sv
#xrun -access +rwc -input ../shm.tcl ex3_polymor_usingcast.sv
#xrun -access +rwc -input ../shm.tcl ex4_polymor_advantage.sv
#xrun -access +rwc -input ../shm.tcl ex4_1_polymor_advantage_extra.sv
#xrun -access +rwc -input ../shm.tcl ex5_polymor_classmemberaccess.sv
#xrun -access +rwc -input ../shm.tcl ex6_polymor_virtualmethod.sv
#xrun -access +rwc -input ../shm.tcl ex6_1_polymor_virtualmethod_extra.sv
#xrun -access +rwc -input ../shm.tcl ex7_polymor_resolveclassmethodaccess.sv
#xrun -access +rwc -input ../shm.tcl ex8_polymor_purevirtual.sv
