#xrun -access +rwc -input ../shm.tcl ex01_0_clocking_declaration.sv
#xrun -access +rwc -input ../shm.tcl ex02_0_clocking_outputdrive.sv
#xrun -access +rwc -input ../shm.tcl ex03_0_clocking_inputsample.sv
#xrun -access +rwc -input ../shm.tcl ex04_0_clocking_skew.sv
#xrun -access +rwc -input ../shm.tcl ex05_0_clocking_example_skew.sv
#xrun -access +rwc -input ../shm.tcl ex06_0_clocking_example_outputskew_sync.sv
#xrun -access +rwc -input ../shm.tcl ex07_0_clocking_multiple_default.sv
xrun -access +rwc -input ../shm.tcl ex08_0_clocking_cycledelay.sv
#xrun -access +rwc -input ../shm.tcl ex09_0_clocking_hierachical_signal.sv
#xrun -access +rwc -input ../shm.tcl ex10_0_clocking_quiz.sv
